variables:
  DOCKER_DRIVER: overlay2
services:
  - name: docker:dind
#    command: ["--insecure-registry=registry.rf:5000"]
build:
  image: docker:latest
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.rf:5000
    - docker build -t registry.rf:5000/test/abc/image:latest .
    - docker push registry.rf:5000/test/abc/image:latest